spring:
  application:
    name: microservices-registry-service
  security:
    user:
      name: ${RS-USERNAME}
      password: ${RS-PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${RS-PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false